In [1]:
import cv2 as cv
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from keras.datasets import mnist
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.activations import linear,relu,sigmoid
from tensorflow.keras.losses import SparseCategoricalCrossentropy


In [3]:
train_data=pd.read_csv('C:/Users/ACER/Desktop/Handwritten Digits Recognition/Data/mnist_train.csv')
test_data=pd.read_csv('C:/Users/ACER/Desktop/Handwritten Digits Recognition/Data/mnist_test.csv')

In [4]:
x_train=train_data.iloc[:,1:].values
y_train=train_data.label.values
x_=test_data.iloc[:,1:]
y_=test_data.label


In [48]:
cv.imshow('image',x_train[1])
cv.waitKey(0)

-1

In [5]:
# Scaling
x_train=x_train/255
x_=x_/255

In [6]:
x_test,x_cv,y_test,y_cv=train_test_split(x_,y_,test_size=0.5,random_state=0)

print(f'''
x_train={x_train.shape}
y_train={y_train.shape}
x_test={x_test.shape}
y_test={y_test.shape}
x_cv={x_cv.shape}
y_cv={y_cv.shape}

''')


x_train=(60000, 784)
y_train=(60000,)
x_test=(5000, 784)
y_test=(5000,)
x_cv=(5000, 784)
y_cv=(5000,)




In [7]:
np.unique(y_train)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [8]:
np.unique(y_test)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [9]:
np.unique(y_cv)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [10]:
x_train.shape

(60000, 784)

In [11]:
y_train.shape

(60000,)

In [12]:
def neural_network_function():
    tf.random.set_seed(20)# Random state
    model_1=Sequential([
        Dense(units=25,activation='relu'),
        Dense(units=15,activation='relu'),
        Dense(units=10,activation='linear')


    ],name='model_1')
    
    
    model_2=Sequential([
        Dense(units=20,activation='relu'),
        Dense(units=12,activation='relu'),
        Dense(units=12,activation='relu'),
        Dense(units=20,activation='relu'),
        Dense(units=10,activation='linear')
        
        
    ],name='model_2')
    model_3=Sequential([
        Dense(units=32,activation='relu'),
        Dense(units=16,activation='relu'),
        Dense(units=8,activation='relu'),
        Dense(units=4,activation='relu'),
#         Dense(units=10,activation='relu'),
        Dense(units=10,activation='linear')
    ],name='model_3')
    
    
    model_list=[model_1,model_2,model_3]
                     
    return model_list

model_list=neural_network_function()

In [23]:
train_error = []
cv_error = []

for i, model in enumerate(model_list):
    print(f'Training Model_{i+1}')

    model.compile(
        loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
        optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
        metrics=['accuracy']
    )

    history = model.fit(x_train, y_train, epochs=40)
    
    _, train_loss = model.evaluate(x_train, y_train)  # calculate train loss
    _, cv_loss = model.evaluate(x_cv, y_cv)  # calculate cv loss
    
    train_error.append(train_loss)
    cv_error.append(cv_loss)


Training Model_1
Epoch 1/40
1875/1875 [==============================] - 5s 2ms/step - loss: 0.0315 - accuracy: 0.9897
Epoch 2/40
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0343 - accuracy: 0.9888
Epoch 3/40
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0315 - accuracy: 0.9898
Epoch 4/40
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0310 - accuracy: 0.9895
Epoch 5/40
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0305 - accuracy: 0.9898
Epoch 6/40
1875/1875 [==============================] - 5s 2ms/step - loss: 0.0298 - accuracy: 0.9901
Epoch 7/40
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0289 - accuracy: 0.9903
Epoch 8/40
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0288 - accuracy: 0.9901
Epoch 9/40
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0275 - accuracy: 0.9906
Epoch 10/40
1875/1875 [==============================] - 4s 2ms/s

1875/1875 [==============================] - 5s 2ms/step - loss: 0.0337 - accuracy: 0.9888
Epoch 39/40
1875/1875 [==============================] - 5s 2ms/step - loss: 0.0294 - accuracy: 0.9903
Epoch 40/40
157/157 [==============================] - 0s 2ms/step - loss: 0.2693 - accuracy: 0.9602
Training Model_3
Epoch 1/40
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0399 - accuracy: 0.9884
Epoch 2/40
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0400 - accuracy: 0.9881
Epoch 3/40
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0366 - accuracy: 0.9890
Epoch 4/40
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0389 - accuracy: 0.9885
Epoch 5/40
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0360 - accuracy: 0.9898
Epoch 6/40
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0358 - accuracy: 0.9894
Epoch 7/40
1875/1875 [==============================] - 5s 2ms/step - loss: 

In [24]:
train_error

[0.9954333305358887, 0.9932500123977661, 0.9936166405677795]

In [25]:
cv_error

[0.9599999785423279, 0.9602000117301941, 0.9521999955177307]

In [26]:
y_pred_cv.shape

(5000, 10)

In [27]:
minimum_loss_train=min(train_error)
min_index_train=train_error.index(minimum_loss_train)


minimum_loss_cv=min(cv_error)
min_index_cv=cv_error.index(minimum_loss_cv)

In [29]:
print(f'''
Minimum Loss is {minimum_loss_train}
Minimum Loss is {minimum_loss_cv}
Best model according to test error is Model:{min_index_train+1}
Best model according to cv error is Model:{min_index_cv+1}

''')


Minimum Loss is 0.9932500123977661
Minimum Loss is 0.9521999955177307
Best model according to test error is Model:2
Best model according to cv error is Model:3




In [32]:
best_model=model_list[min_index_cv]
best_model.compile(
 loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
    metrics=['accuracy']
)
best_model.fit(x_train,y_train,epochs=40)
best_model_prediction=best_model.predict(x_test)
_,test_error=best_model.evaluate(x_test,y_test)


Epoch 1/40
1875/1875 [==============================] - 5s 2ms/step - loss: 0.0173 - accuracy: 0.9950
Epoch 2/40
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0178 - accuracy: 0.9951
Epoch 3/40
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0157 - accuracy: 0.9956
Epoch 4/40
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0178 - accuracy: 0.9951
Epoch 5/40
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0166 - accuracy: 0.9954
Epoch 6/40
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0157 - accuracy: 0.9956
Epoch 7/40
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0155 - accuracy: 0.9956
Epoch 8/40
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0187 - accuracy: 0.9948
Epoch 9/40
1875/1875 [==============================] - 5s 2ms/step - loss: 0.0151 - accuracy: 0.9956
Epoch 10/40
1875/1875 [==============================] - 5s 2ms/step - loss: 0.016

In [33]:
print(f'''
Test Error is :{test_error}
''')


Test Error is :0.9571999907493591



In [35]:
import joblib
joblib.dump(model,'C:/Users/ACER/Desktop/Handwritten Digits Recognition/Models/MNIST.joblib')

['C:/Users/ACER/Desktop/Handwritten Digits Recognition/Models/MNIST.joblib']